void sum(int *arr, int r, int &s, int &p);
void sum(int(*arr)[3], int r, int &s, int &p);
void sum(short(*arr)[3], int r, short &s, short &p);
void sum(double(*arr)[3], int r, double &s, double &p);
void printArr(int *arr, int r);
void printMatrix(int(*arr)[3], int r);
int f(int*arr, int*arrP, int(*func)(int*, int*));
int otr(int*arr, int*arrP);
int pol(int*arr, int*arrP);
int zero(int*arr, int*arrP);
